#!/bin/sh
i=0
if [ $# -eq 0 ]; then
	IP=127.0.0.1
	echo "host ip default: " $IP  
else
	echo "host ip: " $1
	IP=$1	
 
fi
while true; do
i=$[$i+1]
echo "i value " $i      
echo "-------------------------"
echo " Generating Load. 1       ...     "
echo "-------------------------"
# start setting load to learn slow tarnsactions behavior
ab -n 4 -s 360 http://${IP}:3000/recommendations
sleep 10
ab -n 6 -s 360 http://${IP}:3000/userExperience
sleep 8s
echo "-------------------------"
echo "done!!!!!!               "
echo "-------------------------"
done